package controller;

import java.sql.SQLException;
import java.util.List;


/**
 * This class controls the flow of events in homescreen
 * @author ntlinh
 */
public class HomeController extends BaseController{


    /**
     * this method gets all Dock in DB and return back to home to display
     * @return List[Dock]
     * @throws SQLException
     */
    
}
//
//package controller;
//
//import java.sql.SQLException;
//import java.util.ArrayList;
//
//import common.exception.InvalidSearchKeyException;
//import common.exception.NoResultException;
//import controller.search.SearchDockController;
//import controller.search.SearchDockByNameController;
//import entity.dock.Dock;
//
///**
// * This class controls the flow of events in homescreen
// * @author Admin
// *
// */
//public class HomeController extends BaseController {
//  private SearchDockController searchController;
//  
//  public HomeController() {
//	  this.searchController = new SearchDockByNameController(); // set default search mode = by name
//  }
//  
//  /**
//   * this method set search controller
//   * @param searchController
//   */
//  public void setSearchController(SearchDockController searchController) {
//	  this.searchController = searchController;
//  }
//  
//  /**
//   * This method search for a dock match user key.
//   *
//   * @param key the search key user enter
//   * @return ArrayList<Dock> list of the matching dock if there is any
//   * @throws InvalidSearchKeyException if user input blank key
//   * @throws NoResultException if there is no matching dock found
//   * @throws SQLException throws if error occurs during query
//   */
//  public ArrayList<Dock> search(String key) throws InvalidSearchKeyException, NoResultException, SQLException {
//	  ArrayList<Dock> result = this.searchController.searchDock(key);
//	  return result;
//  }
//}


//
//package controller;
//import javafx.fxml.FXML;
//import javafx.fxml.FXMLLoader;
//import javafx.scene.Node;
//import javafx.scene.Parent;
//import javafx.scene.Scene;
//import javafx.scene.control.RadioButton;
//import javafx.scene.control.TextField;
//import javafx.stage.Stage;
//
//import java.awt.event.MouseEvent;
//import java.io.IOException;
//
//import javafx.event.ActionEvent;
//
//public class HomeController {
//	private Stage stage;
//	private Scene scene;
//	private Parent root;
//	@FXML
//	private TextField searchTextField;
//	@FXML
//	private TextField rentCode;
//	@FXML
//	private TextField returnCode;
//	@FXML
//	private RadioButton rButton1, rButton2;
//	
//	public void getSearchOption(ActionEvent event) {
//		if (rButton1.isSelected()) {
//			System.out.println("Search By Name");
//		}
//		else if (rButton2.isSelected()) {
//			System.out.println("Search By Address");
//		}
//	}
//	
//	// Event Listener on Button.onAction
//	@FXML
//	public void btnSearchOnClick(ActionEvent event) throws IOException{
//		String username = searchTextField.getText();
//		System.out.println(username);
//
//	}
//	
//	@FXML
//	public void rowClicked(MouseEvent event) {
//		
//	}
//	// Event Listener on Button.onAction
//	@FXML
//	public void btnRentOnClick(ActionEvent event) {
//		// TODO Autogenerated
//		
//	}
//	// Event Listener on Button.onAction
//	@FXML
//	public void btnReturnOnClick(ActionEvent event) {
//		// TODO Autogenerated
//	}
//}
