import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.RadioButton;
import javafx.scene.control.TextField;
import javafx.stage.Stage;

import java.awt.event.MouseEvent;
import java.io.IOException;

import javafx.event.ActionEvent;

public class HomeSceneController {
	private Stage stage;
	private Scene scene;
	private Parent root;
	@FXML
	private TextField searchTextField;
	@FXML
	private TextField rentCode;
	@FXML
	private TextField returnCode;
	@FXML
	private RadioButton rButton1, rButton2;
	
	public void getSearchOption(ActionEvent event) {
		if (rButton1.isSelected()) {
			System.out.println("Search By Name");
		}
		else if (rButton2.isSelected()) {
			System.out.println("Search By Address");
		}
	}
	
	// Event Listener on Button.onAction
	@FXML
	public void btnSearchOnClick(ActionEvent event) throws IOException{
		String username = seTitle.getText();
		System.out.println(username);
//		
//		FXMLLoader loader = new FXMLLoader(getClass().getResource("eventHandling.fxml"));
//		root = loader.load();
//		
//		EventController eventController = loader.getController();
//		eventController.displayName(username);

//		Parent root = FXMLLoader.load(getClass().getResource("eventHandling.fxml"));
//		stage = (Stage)((Node)event.getSource()).getScene().getWindow();
//		scene = new Scene(root);
//		String css = this.getClass().getResource("application.css").toExternalForm();
//		scene.getStylesheets().add(css);
//		stage.setScene(scene);
//		stage.show();

	}
	
	@FXML
	public void rowClicked(MouseEvent event) {
		
	}
	// Event Listener on Button.onAction
	@FXML
	public void btnRentOnClick(ActionEvent event) {
		// TODO Autogenerated
		
	}
	// Event Listener on Button.onAction
	@FXML
	public void btnReturnOnClick(ActionEvent event) {
		// TODO Autogenerated
	}
}
